{"uuid": "6fc1e09a-80e4-47b4-a89c-d28ef157ac56", "children": ["bed2ef82-af61-4686-852f-ea1ab07ecb37"], "befores": [{"name": "prepare_environment", "status": "broken", "statusDetails": {"message": "PermissionError: [Errno 13] Permission denied: '/nvme/qa_test_models/autotest_model/log/start_restful_internlm2-chat-20b.log'\n", "trace": "  File \"/home/yaoqian/miniconda3/envs/deploy/lib/python3.10/site-packages/pluggy/_callers.py\", line 137, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/yaoqian/miniconda3/envs/deploy/lib/python3.10/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"/home/yaoqian/miniconda3/envs/deploy/lib/python3.10/site-packages/pluggy/_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/yaoqian/miniconda3/envs/deploy/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/yaoqian/miniconda3/envs/deploy/lib/python3.10/site-packages/_pytest/fixtures.py\", line 910, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/nvme/yaoqian/space/lmdeploy/autotest/tools/restful/test_restful_chat_hf_pytorch.py\", line 51, in prepare_environment\n    with open(start_log, 'w') as f:\n"}, "start": 1712112977467, "stop": 1712112980067}], "start": 1712112977467, "stop": 1712112980072}