{"uuid": "7818de0c-7c6f-4ad0-905e-c727fcccfe14", "children": ["5b50948d-148f-48aa-88af-5484c932f9de"], "befores": [{"name": "prepare_environment", "status": "broken", "statusDetails": {"message": "PermissionError: [Errno 13] Permission denied: '/nvme/qa_test_models/autotest_model/log/start_restful_Baichuan2-13B-Chat.log'\n", "trace": "  File \"/home/yaoqian/miniconda3/envs/deploy/lib/python3.10/site-packages/pluggy/_callers.py\", line 137, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/yaoqian/miniconda3/envs/deploy/lib/python3.10/site-packages/_pytest/setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n  File \"/home/yaoqian/miniconda3/envs/deploy/lib/python3.10/site-packages/pluggy/_callers.py\", line 77, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/yaoqian/miniconda3/envs/deploy/lib/python3.10/site-packages/_pytest/fixtures.py\", line 1140, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/yaoqian/miniconda3/envs/deploy/lib/python3.10/site-packages/_pytest/fixtures.py\", line 910, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/nvme/yaoqian/space/lmdeploy/autotest/tools/restful/test_restful_chat_hf_pytorch.py\", line 51, in prepare_environment\n    with open(start_log, 'w') as f:\n"}, "start": 1712112980088, "stop": 1712112982599}], "start": 1712112980088, "stop": 1712112982604}